const express=require("express");const router=express.Router();
const authenticate=require("../middlewares/auth.middleware");const authorize=require("../middlewares/role.middleware");const controller=require("../controllers/event.controller");
router.get("/",authenticate,controller.getEvents);
router.get("/types",authenticate,controller.getEventTypes);
router.get("/:id",authenticate,controller.getEventById);
router.post("/",authenticate,authorize("ORGANIZER","ADMINISTRATOR"),controller.createEvent);
router.post("/:id/submit",authenticate,authorize("ORGANIZER"),controller.submitEvent);
router.post("/:id/approve",authenticate,authorize("ADMINISTRATOR"),controller.approveEvent);
router.post("/:id/reject",authenticate,authorize("ADMINISTRATOR"),controller.rejectEvent);
router.post("/:id/publish",authenticate,authorize("ADMINISTRATOR"),controller.publishEvent);
module.exports=router;
